name: HegelTest
favicon: null
layout_spectrum: 0.9867721933405846
typography_spectrum: 0.4595951857045293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.44957683235406876
  lightness: 0.11531191878020763
  saturation: 0.19721014495007694
  rhythmicContrast: 0.5516351310070604
purpose: []
